// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/signin": {
    params: {};
  };
  "/signout": {
    params: {};
  };
  "/new": {
    params: {};
  };
  "/join/:token": {
    params: {
      "token": string;
    };
  };
  "/w/:slug": {
    params: {
      "slug": string;
    };
  };
  "/w/:slug/c/:ref": {
    params: {
      "slug": string;
      "ref": string;
    };
  };
  "/w/:slug/search": {
    params: {
      "slug": string;
    };
  };
  "/w/:slug/people": {
    params: {
      "slug": string;
    };
  };
  "/w/:slug/you": {
    params: {
      "slug": string;
    };
  };
  "/w/:slug/settings": {
    params: {
      "slug": string;
    };
  };
  "/specimen": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/signin" | "/signout" | "/new" | "/join/:token" | "/w/:slug" | "/w/:slug/c/:ref" | "/w/:slug/search" | "/w/:slug/people" | "/w/:slug/you" | "/w/:slug/settings" | "/specimen";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/signin.tsx": {
    id: "routes/signin";
    page: "/signin";
  };
  "routes/signout.tsx": {
    id: "routes/signout";
    page: "/signout";
  };
  "routes/new-workspace.tsx": {
    id: "routes/new-workspace";
    page: "/new";
  };
  "routes/join.tsx": {
    id: "routes/join";
    page: "/join/:token";
  };
  "routes/workspace.tsx": {
    id: "routes/workspace";
    page: "/w/:slug" | "/w/:slug/c/:ref" | "/w/:slug/search" | "/w/:slug/people" | "/w/:slug/you" | "/w/:slug/settings";
  };
  "routes/workspace-home.tsx": {
    id: "routes/workspace-home";
    page: "/w/:slug";
  };
  "routes/channel.tsx": {
    id: "routes/channel";
    page: "/w/:slug/c/:ref";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/w/:slug/search";
  };
  "routes/members.tsx": {
    id: "routes/members";
    page: "/w/:slug/people";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/w/:slug/you";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/w/:slug/settings";
  };
  "routes/specimen.tsx": {
    id: "routes/specimen";
    page: "/specimen";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/signin": typeof import("./app/routes/signin.tsx");
  "routes/signout": typeof import("./app/routes/signout.tsx");
  "routes/new-workspace": typeof import("./app/routes/new-workspace.tsx");
  "routes/join": typeof import("./app/routes/join.tsx");
  "routes/workspace": typeof import("./app/routes/workspace.tsx");
  "routes/workspace-home": typeof import("./app/routes/workspace-home.tsx");
  "routes/channel": typeof import("./app/routes/channel.tsx");
  "routes/search": typeof import("./app/routes/search.tsx");
  "routes/members": typeof import("./app/routes/members.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/specimen": typeof import("./app/routes/specimen.tsx");
};